/* global window */
/* ============================================================
   LANDING — copy pack #2 (deeper modules)
   Merged into LANDING_COPY at load so the FR/EN toggle covers it too.
   Kept in its own file to avoid editing the large base dictionary.
============================================================ */
const __LANDING_COPY2 = {
  en: {
    groups: {
      rituals: "Daily rituals", productivity: "Productivity", calendar: "Calendar & sharing",
      wellbeing: "Well-being", insights: "Insights & automation", personalize: "Make it yours",
    },

    daily: {
      tag: "Daily planning ritual",
      title: "Turn a fuzzy list into a real day.",
      desc: "A six-step assistant walks you from brain-dump to a day placed in your calendar — one decision at a time, in about two minutes.",
      bullets: ["Six guided steps, zero overwhelm", "Honest time estimates", "Auto-placed around your energy"],
      hint: "↓ Walk through the six steps",
      placeholder: "Add a task…",
      addedNote: "Your tasks flow through every step",
      steps: [
        { k: "Add", d: "Brain-dump every task" },
        { k: "Estimate", d: "How long will it take?" },
        { k: "Fill", d: "Pull in habits & events" },
        { k: "Prioritize", d: "Urgent × important" },
        { k: "Schedule", d: "Drop onto the calendar" },
        { k: "Document", d: "Note the plan for tomorrow" },
      ],
    },

    tasksPro: {
      tag: "Tasks · 5 views & boards",
      title: "The same work, five angles.",
      desc: "List to check off, Boards for flow, Timeline for deadlines, Calendar to schedule, Stats for perspective. Drag cards across a Kanban with WIP limits and assignees — with a little celebration when one lands in Done.",
      bullets: ["List · Board · Timeline · Calendar · Stats", "Kanban with WIP limits & assignees", "Custom arrival animation per column"],
      hint: "↓ Switch views, then drag a card to Done",
      views: ["List", "Board", "Timeline", "Calendar", "Stats"],
      columns: ["Backlog", "In progress", "Done"],
      wip: "WIP",
      cards: [
        { t: "Q2 presentation", who: "RA", c: "263 70% 60%", p: "high" },
        { t: "Refactor auth", who: "LB", c: "217 91% 60%", p: "med" },
        { t: "Review PR #142", who: "MT", c: "38 92% 55%", p: "med" },
        { t: "API docs", who: "RA", c: "142 70% 50%", p: "low" },
      ],
      fxLabel: "Arrival FX",
      fxOptions: ["Confetti", "Glow", "Check", "Bounce"],
    },

    focusPro: {
      tag: "Focus · deep work",
      title: "One task, locked in. Music on. Go.",
      desc: "Lock the top task to your session, watch the ring pace focus and breaks, and let DPM hush distractions — your music even dips on breaks. Hyperfocus chains blocks when you're in the zone.",
      bullets: ["Lock a task to the session", "Focus / break ring + break counter", "Connect Spotify · Apple · YouTube"],
      hint: "↓ Lock a task, press play, connect music",
      queue: "Session queue",
      locked: "Locked to session",
      lock: "Lock",
      breaks: "breaks",
      hyperfocus: "Hyperfocus",
      tasks: ["Write the Q2 deck", "Refactor auth module", "Review 2 PRs"],
      breakLabel: "Break",
      skip: "Skip break",
      lockedNote: "Locked in — pause to change task or music",
      durations: "Durations",
      focusLen: "Focus",
      breakLen: "Break",
      presets: "Presets",
      min: "min",
      editHint: "Double-click a number to set your own duration",
      breakToast: "Break time ☕",
      focusToast: "Back to focus ↑",
      demoBadge: "Demo speed",
    },

    music: {
      label: "Focus music",
      connect: "Connect",
      connected: "Connected",
      friendly: "Focus-friendly",
      nowPlaying: "Now playing",
      muteBreak: "Mute on break",
      mutedNow: "Muted for your break",
      activeNow: "active",
      services: ["Spotify", "Apple Music", "YouTube Music"],
      playlists: [
        { n: "Deep Work", c: 64, score: 92, ha: 217, hb: 190 },
        { n: "Lofi Chill", c: 120, score: 85, ha: 263, hb: 305 },
        { n: "Piano & rain", c: 72, score: 78, ha: 228, hb: 262 },
        { n: "Liked songs", c: 248, score: 44, ha: 330, hb: 280 },
      ],
      track: "Ambient layer",
    },

    calendarPro: {
      tag: "Calendar · plan & share",
      title: "Drag a task in. Get a slot. Share it.",
      desc: "Drag an unscheduled task onto the week and it becomes a timed block. DPM proposes the best free slot around your energy — and you can share a slot with anyone in a click, or auto-plan tomorrow.",
      bullets: ["Events, tasks & focus sessions in one grid", "Smart slot suggestions", "Share a slot or plan tomorrow in a tap"],
      hint: "↓ Drag a task from the inbox onto the grid",
      inbox: "Unscheduled",
      suggest: "DPM suggests",
      suggestSub: "Free · best for deep work",
      place: "Place it",
      share: "Share slot",
      planTomorrow: "Plan tomorrow",
      legend: { event: "Event", task: "Task", focus: "Focus" },
      shared: "Link copied — anyone can pick a time",
      days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      tasks: ["Q2 presentation · 3h", "API doc update · 1h", "Read ch. 4 · 20m"],
    },

    spaces: {
      tag: "Spaces · one app, many contexts",
      title: "Work, personal, studies — cleanly apart.",
      desc: "A Space scopes the whole app — calendars, tasks, habits, goals and rules. Switch in a click and everything re-tints. Share a Space with the right people and grant per-module rights.",
      bullets: ["Scope everything to a context", "Per-space ambient color", "Granular sharing & assignment"],
      hint: "↓ Switch space — the page re-tints",
      list: [
        { id: "all", n: "All", icon: "Layers", c: "263 70% 60%", hours: "All hours" },
        { id: "pro", n: "Professional", icon: "Briefcase", c: "217 91% 60%", hours: "09:00 – 17:00" },
        { id: "perso", n: "Personal", icon: "Heart", c: "330 80% 60%", hours: "Evenings & weekends" },
        { id: "etudes", n: "Studies", icon: "GraduationCap", c: "38 92% 55%", hours: "Evenings" },
      ],
      union: "union",
      members: "Shared with",
      modules: ["Calendars", "Tasks", "Priorities", "Goals", "Habits"],
      people: [
        { n: "Ralph Aubry", r: "Owner", i: "RA", c: "263 70% 55%" },
        { n: "Léa Bouchard", r: "Edit", i: "LB", c: "217 91% 55%" },
        { n: "Marc Therrien", r: "Invited", i: "MT", c: "38 92% 50%" },
      ],
      invite: "Invite",
      scoped: "items scoped",
      levels: ["No access", "View", "Edit"],
      permsFor: "Access for",
      tapHint: "Tap a person, then set their access per module",
    },

    rules: {
      tag: "Automation · If… Then…",
      title: "Your schedule defends itself.",
      desc: "Rules add buffers, protect focus and insert breaks without a thought. Start from a template, flip it on, and watch the run counter climb.",
      bullets: ["If trigger → then action", "A run counter on every rule", "Ready-made templates"],
      hint: "↓ Toggle a rule on or off",
      items: [
        { n: "Focus time", d: "Protects blocks for deep work", icon: "Shield", c: "263 70% 60%", runs: 12, on: true },
        { n: "Lunch break", d: "Inserts a lunch break daily", icon: "Coffee", c: "142 70% 50%", runs: 8, on: true },
        { n: "Meeting buffer", d: "Adds 15 min after each meeting", icon: "Zap", c: "20 90% 55%", runs: 3, on: true },
        { n: "Tuesday overload", d: "Moves low-priority off busy Tuesdays", icon: "Activity", c: "0 84% 60%", runs: 0, on: false },
      ],
      runs: "runs",
      templates: "Templates",
    },

    health: {
      tag: "Health & sleep · chronotype",
      title: "Plan with your body, not against it.",
      desc: "Connect your watch and DPM reads sleep, resting heart rate, activity and recovery — then learns your chronotype and tells you when to schedule your hardest work.",
      bullets: ["Sleep, resting HR, steps & recovery", "Learns your chronotype", "Sleep → energy correlation"],
      tabs: ["Vitals", "Sleep", "Chronotype"],
      synced: "synced 4 min ago",
      details: "Details",
      vitals: [
        { k: "sleep", label: "Sleep", v: "7h 24", sub: "Good · +38 min", c: "263 70% 62%", icon: "Moon" },
        { k: "hr", label: "Resting HR", v: "58", unit: "bpm", sub: "Stable · normal", c: "0 80% 62%", icon: "Heart" },
        { k: "steps", label: "Activity · steps", v: "6,240", sub: "62% of goal", c: "217 85% 62%", icon: "Zap" },
        { k: "recovery", label: "Recovery", v: "82", unit: "/100", sub: "High · ready", c: "142 70% 52%", icon: "Activity" },
      ],
      chronotypes: [
        { id: "lark", n: "Early bird", d: "Peak in the morning, early to bed.", hrs: "05:00 – 21:00", icon: "Sun", on: true },
        { id: "third", n: "Third bird", d: "Best around the middle of the day.", hrs: "07:00 – 23:00", icon: "Bird", on: false },
        { id: "owl", n: "Night owl", d: "Sharper in the evening.", hrs: "10:00 – 02:00", icon: "Owl", on: false },
      ],
      ai: "Great recovery → place your most demanding task this morning. DPM suggests an optimal slot at ",
      aiTime: "09:00",
      seeSlot: "See the slot",
      devices: ["Apple Watch", "Oura", "Fitbit", "Garmin"],
      sync: { label: "Sync your health data", now: "Sync now", just: "synced just now", auto: "Auto-sync from your phone — Apple Health or Android" },
      sources: [
        { n: "Apple Health", c: "0 0% 82%", on: true },
        { n: "Google Fit", c: "142 70% 48%", on: false },
        { n: "Samsung Health", c: "217 85% 55%", on: false },
        { n: "Apple Watch", c: "0 0% 82%", on: true },
        { n: "Oura Ring", c: "263 70% 60%", on: false },
      ],
    },

    goalsPro: {
      tag: "Goals · framed SMART",
      title: "From a vague wish to measured progress.",
      desc: "Every goal shows where you stand against its target and whether it's framed to succeed. The five S·M·A·R·T badges flag what to fix; linked habits move it forward daily.",
      bullets: ["Concrete progress (15/24)", "S·M·A·R·T quality badges", "Linked to the habits that move it"],
      smart: ["S", "M", "A", "R", "T"],
      smartFull: ["Specific", "Measurable", "Achievable", "Realistic", "Time-bound"],
      items: [
        { t: "Read 24 books", cat: "Personal", cur: 15, max: 24, unit: "books", c: "263 70% 60%", smart: [1,1,1,1,1], linked: "Reading" },
        { t: "Run 50h / month", cat: "Health", cur: 32, max: 50, unit: "h", c: "217 91% 60%", smart: [1,1,1,1,1], linked: "Running" },
        { t: "Learn Rust", cat: "Learning", cur: 8, max: 30, unit: "sessions", c: "20 90% 55%", smart: [1,1,1,0,1], linked: null },
      ],
      linkedLabel: "Linked habit",
    },

    reviews: {
      label: "Loved by busy people",
      title: "Real users, real routines.",
      sub: "Reviews from the field — plus the one tip each of them swears by.",
      items: [
        { name: "Sofia R.", role: "Startup founder", icon: "Briefcase", stars: 5, text: "The Rules engine alone gave me back my mornings — buffers between meetings are automatic now.", tip: "Start with the “Meeting buffer” template." },
        { name: "Marcus L.", role: "Engineering student", icon: "GraduationCap", stars: 5, text: "The daily planning ritual is the only thing that survived exam season. Two minutes, sorted.", tip: "Estimate tasks honestly — the calendar fills itself." },
        { name: "Alex P.", role: "Freelancer", icon: "Compass", stars: 5, text: "Spaces keep client work and personal life apart without two apps. Sharing a slot closes deals faster.", tip: "One Space per client, shared read-only." },
        { name: "Priya K.", role: "Team lead", icon: "Users", stars: 4, text: "Health + chronotype changed how I schedule deep work — my 1-1s no longer eat my focus hours.", tip: "Connect your watch for the energy curve." },
      ],
    },
  },

  fr: {
    groups: {
      rituals: "Rituels quotidiens", productivity: "Productivité", calendar: "Agenda & partage",
      wellbeing: "Bien-être", insights: "Analytics & automatisation", personalize: "À votre image",
    },

    daily: {
      tag: "Rituel de planification",
      title: "Transformez une liste floue en vraie journée.",
      desc: "Un assistant en six étapes vous mène du vide-cerveau à une journée posée dans l'agenda — une décision à la fois, en deux minutes environ.",
      bullets: ["Six étapes guidées, zéro surcharge", "Estimations de temps honnêtes", "Placé autour de votre énergie"],
      hint: "↓ Parcourez les six étapes",
      placeholder: "Ajouter une tâche…",
      addedNote: "Vos tâches traversent chaque étape",
      steps: [
        { k: "Ajouter", d: "Videz toutes les tâches" },
        { k: "Estimer", d: "Combien de temps ?" },
        { k: "Remplir", d: "Tirez habitudes & événements" },
        { k: "Prioriser", d: "Urgent × important" },
        { k: "Planifier", d: "Déposez dans l'agenda" },
        { k: "Documenter", d: "Notez le plan de demain" },
      ],
    },

    tasksPro: {
      tag: "Tâches · 5 vues & tableaux",
      title: "Le même travail, cinq angles.",
      desc: "Liste pour cocher, Tableaux pour le flux, Timeline pour les échéances, Calendrier pour planifier, Stats pour le recul. Glissez les cartes dans un Kanban avec limites WIP et assignations — avec une petite célébration à l'arrivée en Terminé.",
      bullets: ["Liste · Tableau · Timeline · Calendrier · Stats", "Kanban avec limites WIP & assignations", "Animation d'arrivée personnalisée par colonne"],
      hint: "↓ Changez de vue, puis glissez une carte vers Terminé",
      views: ["Liste", "Tableau", "Timeline", "Calendrier", "Stats"],
      columns: ["À faire", "En cours", "Terminé"],
      wip: "WIP",
      cards: [
        { t: "Présentation T2", who: "RA", c: "263 70% 60%", p: "high" },
        { t: "Refactor auth", who: "LB", c: "217 91% 60%", p: "med" },
        { t: "Revue PR #142", who: "MT", c: "38 92% 55%", p: "med" },
        { t: "Doc API", who: "RA", c: "142 70% 50%", p: "low" },
      ],
      fxLabel: "Animation d'arrivée",
      fxOptions: ["Confettis", "Lueur", "Coche", "Rebond"],
    },

    focusPro: {
      tag: "Focus · deep work",
      title: "Une tâche, verrouillée. Musique. C'est parti.",
      desc: "Verrouillez la tâche du haut à votre session, l'anneau cadence focus et pauses, et DPM fait taire les distractions — la musique baisse même pendant les pauses. L'hyperfocus enchaîne les blocs quand vous êtes lancé.",
      bullets: ["Verrouillez une tâche à la session", "Anneau focus / pause + compteur de pauses", "Connectez Spotify · Apple · YouTube"],
      hint: "↓ Verrouillez une tâche, lancez, connectez la musique",
      queue: "File de session",
      locked: "Verrouillée à la session",
      lock: "Verrouiller",
      breaks: "pauses",
      hyperfocus: "Hyperfocus",
      tasks: ["Écrire le deck T2", "Refactor module auth", "Relire 2 PR"],
      breakLabel: "Pause",
      skip: "Passer la pause",
      lockedNote: "Verrouillé — mettez en pause pour changer",
      durations: "Durées",
      focusLen: "Focus",
      breakLen: "Pause",
      presets: "Préréglages",
      min: "min",
      editHint: "Double-cliquez un nombre pour définir votre durée",
      breakToast: "C'est la pause ☕",
      focusToast: "Retour au focus ↑",
      demoBadge: "Vitesse démo",
    },

    music: {
      label: "Musique de focus",
      connect: "Connecter",
      connected: "Connecté",
      friendly: "Propice au focus",
      nowPlaying: "En lecture",
      muteBreak: "Couper en pause",
      mutedNow: "Coupé pendant la pause",
      activeNow: "actif",
      services: ["Spotify", "Apple Music", "YouTube Music"],
      playlists: [
        { n: "Deep Work", c: 64, score: 92, ha: 217, hb: 190 },
        { n: "Lofi Chill", c: 120, score: 85, ha: 263, hb: 305 },
        { n: "Piano & pluie", c: 72, score: 78, ha: 228, hb: 262 },
        { n: "Titres likés", c: 248, score: 44, ha: 330, hb: 280 },
      ],
      track: "Nappe ambiante",
    },

    calendarPro: {
      tag: "Agenda · planifier & partager",
      title: "Glissez une tâche. Recevez un créneau. Partagez-le.",
      desc: "Glissez une tâche non planifiée sur la semaine et elle devient un bloc horaire. DPM propose le meilleur créneau libre selon votre énergie — partagez un créneau en un clic, ou planifiez demain automatiquement.",
      bullets: ["Événements, tâches & sessions de focus dans une grille", "Suggestions de créneaux intelligentes", "Partagez un créneau ou planifiez demain en un tap"],
      hint: "↓ Glissez une tâche de la boîte sur la grille",
      inbox: "Non planifié",
      suggest: "DPM suggère",
      suggestSub: "Libre · idéal deep work",
      place: "Placer",
      share: "Partager le créneau",
      planTomorrow: "Planifier demain",
      legend: { event: "Événement", task: "Tâche", focus: "Focus" },
      shared: "Lien copié — chacun choisit son heure",
      days: ["Lun", "Mar", "Mer", "Jeu", "Ven"],
      tasks: ["Présentation T2 · 3h", "MàJ doc API · 1h", "Lire ch. 4 · 20m"],
    },

    spaces: {
      tag: "Espaces · une app, plusieurs contextes",
      title: "Pro, perso, études — bien séparés.",
      desc: "Un Espace cadre toute l'app — agendas, tâches, habitudes, objectifs et règles. Basculez en un clic et tout se re-teinte. Partagez un Espace avec les bonnes personnes et accordez des droits par module.",
      bullets: ["Cadrez tout selon un contexte", "Couleur d'ambiance par espace", "Partage & assignation granulaires"],
      hint: "↓ Changez d'espace — la page se re-teinte",
      list: [
        { id: "all", n: "Tous", icon: "Layers", c: "263 70% 60%", hours: "Toutes les heures" },
        { id: "pro", n: "Professionnel", icon: "Briefcase", c: "217 91% 60%", hours: "09:00 – 17:00" },
        { id: "perso", n: "Personnel", icon: "Heart", c: "330 80% 60%", hours: "Soirs & week-ends" },
        { id: "etudes", n: "Études", icon: "GraduationCap", c: "38 92% 55%", hours: "Soirs" },
      ],
      union: "union",
      members: "Partagé avec",
      modules: ["Agendas", "Tâches", "Priorités", "Objectifs", "Habitudes"],
      people: [
        { n: "Ralph Aubry", r: "Propriétaire", i: "RA", c: "263 70% 55%" },
        { n: "Léa Bouchard", r: "Édition", i: "LB", c: "217 91% 55%" },
        { n: "Marc Therrien", r: "Invité", i: "MT", c: "38 92% 50%" },
      ],
      invite: "Inviter",
      scoped: "éléments cadrés",
      levels: ["Aucun", "Vue", "Édition"],
      permsFor: "Accès de",
      tapHint: "Touchez une personne, puis réglez son accès par module",
    },

    rules: {
      tag: "Automatisation · Si… Alors…",
      title: "Votre agenda se défend tout seul.",
      desc: "Les règles ajoutent des marges, protègent le focus et insèrent vos pauses sans y penser. Partez d'un modèle, activez-le, et regardez le compteur grimper.",
      bullets: ["Si déclencheur → alors action", "Un compteur d'exécutions par règle", "Modèles prêts à l'emploi"],
      hint: "↓ Activez ou désactivez une règle",
      items: [
        { n: "Temps de focus", d: "Protège les blocs de deep work", icon: "Shield", c: "263 70% 60%", runs: 12, on: true },
        { n: "Pause déjeuner", d: "Insère une pause déjeuner chaque jour", icon: "Coffee", c: "142 70% 50%", runs: 8, on: true },
        { n: "Marge réunion", d: "Ajoute 15 min après chaque réunion", icon: "Zap", c: "20 90% 55%", runs: 3, on: true },
        { n: "Surcharge du mardi", d: "Décale le peu prioritaire des mardis chargés", icon: "Activity", c: "0 84% 60%", runs: 0, on: false },
      ],
      runs: "exéc.",
      templates: "Modèles",
    },

    health: {
      tag: "Santé & sommeil · chronotype",
      title: "Planifiez avec votre corps, pas contre lui.",
      desc: "Connectez votre montre et DPM lit le sommeil, la FC au repos, l'activité et la récupération — puis apprend votre chronotype et vous dit quand placer votre travail le plus exigeant.",
      bullets: ["Sommeil, FC repos, pas & récupération", "Apprend votre chronotype", "Corrélation sommeil → énergie"],
      tabs: ["Vitaux", "Sommeil", "Chronotype"],
      synced: "sync il y a 4 min",
      details: "Détails",
      vitals: [
        { k: "sleep", label: "Sommeil", v: "7 h 24", sub: "Bonne · +38 min", c: "263 70% 62%", icon: "Moon" },
        { k: "hr", label: "FC repos", v: "58", unit: "bpm", sub: "Stable · normal", c: "0 80% 62%", icon: "Heart" },
        { k: "steps", label: "Activité · pas", v: "6 240", sub: "62 % de l'objectif", c: "217 85% 62%", icon: "Zap" },
        { k: "recovery", label: "Récupération", v: "82", unit: "/100", sub: "Élevée · prêt", c: "142 70% 52%", icon: "Activity" },
      ],
      chronotypes: [
        { id: "lark", n: "Alouette", d: "Pic le matin, couché tôt.", hrs: "05:00 – 21:00", icon: "Sun", on: true },
        { id: "third", n: "Troisième oiseau", d: "Au mieux au milieu de la journée.", hrs: "07:00 – 23:00", icon: "Bird", on: false },
        { id: "owl", n: "Hibou", d: "Plus vif en soirée.", hrs: "10:00 – 02:00", icon: "Owl", on: false },
      ],
      ai: "Bonne récupération → placez votre tâche la plus exigeante ce matin. DPM propose un créneau optimal à ",
      aiTime: "09:00",
      seeSlot: "Voir le créneau",
      devices: ["Apple Watch", "Oura", "Fitbit", "Garmin"],
      sync: { label: "Synchronisez vos données santé", now: "Synchroniser", just: "synchronisé à l'instant", auto: "Sync auto depuis votre téléphone — Apple Santé ou Android" },
      sources: [
        { n: "Apple Santé", c: "0 0% 82%", on: true },
        { n: "Google Fit", c: "142 70% 48%", on: false },
        { n: "Samsung Health", c: "217 85% 55%", on: false },
        { n: "Apple Watch", c: "0 0% 82%", on: true },
        { n: "Oura Ring", c: "263 70% 60%", on: false },
      ],
    },

    goalsPro: {
      tag: "Objectifs · cadrés SMART",
      title: "D'un vœu flou à une progression mesurée.",
      desc: "Chaque objectif montre où vous en êtes face à sa cible et s'il est cadré pour réussir. Les cinq badges S·M·A·R·T signalent quoi corriger ; les habitudes liées le font avancer chaque jour.",
      bullets: ["Progression concrète (15/24)", "Badges qualité S·M·A·R·T", "Liés aux habitudes qui les font avancer"],
      smart: ["S", "M", "A", "R", "T"],
      smartFull: ["Spécifique", "Mesurable", "Atteignable", "Réaliste", "Temporel"],
      items: [
        { t: "Lire 24 livres", cat: "Personnel", cur: 15, max: 24, unit: "livres", c: "263 70% 60%", smart: [1,1,1,1,1], linked: "Lecture" },
        { t: "Courir 50h / mois", cat: "Santé", cur: 32, max: 50, unit: "h", c: "217 91% 60%", smart: [1,1,1,1,1], linked: "Course" },
        { t: "Apprendre Rust", cat: "Apprentissage", cur: 8, max: 30, unit: "sessions", c: "20 90% 55%", smart: [1,1,1,0,1], linked: null },
      ],
      linkedLabel: "Habitude liée",
    },

    reviews: {
      label: "Adoré par les gens occupés",
      title: "De vrais utilisateurs, de vraies routines.",
      sub: "Des avis du terrain — avec l'astuce que chacun jure d'utiliser.",
      items: [
        { name: "Sofia R.", role: "Fondatrice de startup", icon: "Briefcase", stars: 5, text: "Le moteur de règles à lui seul m'a rendu mes matins — les marges entre réunions sont automatiques.", tip: "Commencez par le modèle « Marge réunion »." },
        { name: "Marcus L.", role: "Étudiant ingénieur", icon: "GraduationCap", stars: 5, text: "Le rituel de planification est la seule chose qui a survécu aux examens. Deux minutes, réglé.", tip: "Estimez honnêtement — l'agenda se remplit seul." },
        { name: "Alex P.", role: "Freelance", icon: "Compass", stars: 5, text: "Les Espaces séparent clients et vie perso sans deux apps. Partager un créneau conclut plus vite.", tip: "Un Espace par client, partagé en lecture." },
        { name: "Priya K.", role: "Team lead", icon: "Users", stars: 4, text: "Santé + chronotype ont changé ma façon de placer le deep work — mes 1-1 ne mangent plus mon focus.", tip: "Connectez votre montre pour la courbe d'énergie." },
      ],
    },
  },
};

if (typeof window !== "undefined" && window.LANDING_COPY) {
  Object.assign(window.LANDING_COPY.en, __LANDING_COPY2.en);
  Object.assign(window.LANDING_COPY.fr, __LANDING_COPY2.fr);
}
